# Generated by Django 4.2.13 on 2024-06-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='USERS',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('fullname', models.CharField(max_length=128, unique=True)),
                ('username', models.CharField(max_length=128, unique=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('phone', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
                ('admin', models.CharField(default='user', max_length=15)),
                ('enable', models.BooleanField(default=True)),
                ('loginstatus', models.BooleanField(default=False)),
                ('lastlogin', models.DateTimeField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
        ),
    ]
