# Generated by Django 4.2.13 on 2024-06-26 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mzApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('remindname', models.CharField(max_length=100, unique=True)),
                ('url', models.CharField(max_length=150)),
                ('reminddesc', models.CharField(max_length=150)),
                ('remindtype', models.CharField(max_length=10)),
                ('expiredate', models.DateTimeField(blank=True, null=True)),
                ('remindbefor', models.IntegerField(default=10)),
                ('groups', models.CharField(default=None, max_length=100, null=True)),
                ('remainingdays', models.CharField(max_length=100, null=True)),
                ('lastupdate', models.DateTimeField(blank=True, null=True)),
                ('remindlog', models.TextField()),
                ('notification', models.BooleanField(default=True)),
                ('prev_alertstatus', models.BooleanField(default=False)),
                ('alertstatus', models.BooleanField(default=False)),
                ('createby_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mzApp.users')),
            ],
        ),
    ]
