# Generated by Django 4.2.13 on 2024-06-28 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mzApp', '0002_reminder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('helpname', models.CharField(max_length=255, unique=True)),
                ('helpdesc', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='DailyTasksReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('report', models.TextField(default='')),
                ('reportdate', models.DateTimeField(blank=True, null=True)),
                ('lastupdate', models.DateTimeField(blank=True, null=True)),
                ('createby', models.CharField(default=None, max_length=100)),
                ('createby_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mzApp.users')),
            ],
        ),
        migrations.CreateModel(
            name='DailyTasks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('task', models.TextField(unique=True)),
                ('taskhelp', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mzApp.help')),
            ],
        ),
    ]
