# Generated by Django 4.2.13 on 2024-06-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mzApp', '0003_help_dailytasksreport_dailytasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='helpdesc',
            field=models.TextField(default=None, null=True),
        ),
    ]
