# Generated by Django 4.2.13 on 2024-07-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mzApp', '0005_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='mouaz/mzProject/mzApp/images/'),
        ),
    ]
