# Generated by Django 4.2.13 on 2024-07-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mzApp', '0006_alter_image_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='help',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='mzApp/images/'),
        ),
    ]
