# Generated by Django 4.2.13 on 2024-07-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mzApp', '0007_delete_image_help_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='mzApp/images/'),
        ),
    ]
